export const EXCEL_TO_DB_MAPPING = {
  'Category': 'category_name',
  'City': 'city',
  'Country': 'country',
  'Customer Name': 'customer_name',
  'Manufacturer': 'manufacturer',
  'Order Date': 'order_date',
  'Order ID': 'order_id',
  'Postal Code': 'postal_code',
  'Product Name': 'product_name',
  'Region': 'region',
  'Segment': 'segment_name',
  'Ship Date': 'ship_date',
  'Ship Mode': 'ship_mode',
  'State': 'state',
  'Sub-Category': 'sub_category_name',
  'Discount': 'discount',
  'Number of Records': 'number_of_record',
  'Profit': 'profit',
  'Profit Ratio': 'profit_ratio',
  'Quantity': 'quantity',
  'Sales': 'sales_amount',
}